// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for CloudInstanceMode.
const (
	CloudInstanceModeReplicated CloudInstanceMode = "replicated"
	CloudInstanceModeSingle     CloudInstanceMode = "single"
)

// Valid indicates whether the value is a known member of the CloudInstanceMode enum.
func (e CloudInstanceMode) Valid() bool {
	switch e {
	case CloudInstanceModeReplicated:
		return true
	case CloudInstanceModeSingle:
		return true
	default:
		return false
	}
}

// Defines values for CloudInstanceStatus.
const (
	CloudInstanceStatusDegraded       CloudInstanceStatus = "degraded"
	CloudInstanceStatusDeleted        CloudInstanceStatus = "deleted"
	CloudInstanceStatusDeprovisioning CloudInstanceStatus = "deprovisioning"
	CloudInstanceStatusFailed         CloudInstanceStatus = "failed"
	CloudInstanceStatusPending        CloudInstanceStatus = "pending"
	CloudInstanceStatusProvisioning   CloudInstanceStatus = "provisioning"
	CloudInstanceStatusReady          CloudInstanceStatus = "ready"
	CloudInstanceStatusSuspended      CloudInstanceStatus = "suspended"
	CloudInstanceStatusUpdating       CloudInstanceStatus = "updating"
)

// Valid indicates whether the value is a known member of the CloudInstanceStatus enum.
func (e CloudInstanceStatus) Valid() bool {
	switch e {
	case CloudInstanceStatusDegraded:
		return true
	case CloudInstanceStatusDeleted:
		return true
	case CloudInstanceStatusDeprovisioning:
		return true
	case CloudInstanceStatusFailed:
		return true
	case CloudInstanceStatusPending:
		return true
	case CloudInstanceStatusProvisioning:
		return true
	case CloudInstanceStatusReady:
		return true
	case CloudInstanceStatusSuspended:
		return true
	case CloudInstanceStatusUpdating:
		return true
	default:
		return false
	}
}

// Defines values for CloudInstanceTier.
const (
	CloudInstanceTierPro      CloudInstanceTier = "pro"
	CloudInstanceTierStandard CloudInstanceTier = "standard"
	CloudInstanceTierStarter  CloudInstanceTier = "starter"
)

// Valid indicates whether the value is a known member of the CloudInstanceTier enum.
func (e CloudInstanceTier) Valid() bool {
	switch e {
	case CloudInstanceTierPro:
		return true
	case CloudInstanceTierStandard:
		return true
	case CloudInstanceTierStarter:
		return true
	default:
		return false
	}
}

// Defines values for CloudInstanceVersionPolicy.
const (
	CloudInstanceVersionPolicyMajorManual CloudInstanceVersionPolicy = "major_manual"
	CloudInstanceVersionPolicyMinorAuto   CloudInstanceVersionPolicy = "minor_auto"
	CloudInstanceVersionPolicyPatchAuto   CloudInstanceVersionPolicy = "patch_auto"
	CloudInstanceVersionPolicyPinned      CloudInstanceVersionPolicy = "pinned"
)

// Valid indicates whether the value is a known member of the CloudInstanceVersionPolicy enum.
func (e CloudInstanceVersionPolicy) Valid() bool {
	switch e {
	case CloudInstanceVersionPolicyMajorManual:
		return true
	case CloudInstanceVersionPolicyMinorAuto:
		return true
	case CloudInstanceVersionPolicyPatchAuto:
		return true
	case CloudInstanceVersionPolicyPinned:
		return true
	default:
		return false
	}
}

// Defines values for CloudInstanceVersionUpgradeStatus.
const (
	CloudInstanceVersionUpgradeStatusBlocked CloudInstanceVersionUpgradeStatus = "blocked"
	CloudInstanceVersionUpgradeStatusFailed  CloudInstanceVersionUpgradeStatus = "failed"
	CloudInstanceVersionUpgradeStatusIdle    CloudInstanceVersionUpgradeStatus = "idle"
	CloudInstanceVersionUpgradeStatusPending CloudInstanceVersionUpgradeStatus = "pending"
	CloudInstanceVersionUpgradeStatusRolling CloudInstanceVersionUpgradeStatus = "rolling"
)

// Valid indicates whether the value is a known member of the CloudInstanceVersionUpgradeStatus enum.
func (e CloudInstanceVersionUpgradeStatus) Valid() bool {
	switch e {
	case CloudInstanceVersionUpgradeStatusBlocked:
		return true
	case CloudInstanceVersionUpgradeStatusFailed:
		return true
	case CloudInstanceVersionUpgradeStatusIdle:
		return true
	case CloudInstanceVersionUpgradeStatusPending:
		return true
	case CloudInstanceVersionUpgradeStatusRolling:
		return true
	default:
		return false
	}
}

// Defines values for OrganizationStatus.
const (
	OrganizationStatusActive  OrganizationStatus = "active"
	OrganizationStatusDeleted OrganizationStatus = "deleted"
	OrganizationStatusFrozen  OrganizationStatus = "frozen"
)

// Valid indicates whether the value is a known member of the OrganizationStatus enum.
func (e OrganizationStatus) Valid() bool {
	switch e {
	case OrganizationStatusActive:
		return true
	case OrganizationStatusDeleted:
		return true
	case OrganizationStatusFrozen:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	UserStatusActive    UserStatus = "active"
	UserStatusDeleted   UserStatus = "deleted"
	UserStatusSuspended UserStatus = "suspended"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case UserStatusActive:
		return true
	case UserStatusDeleted:
		return true
	case UserStatusSuspended:
		return true
	default:
		return false
	}
}

// CloudInstance defines model for CloudInstance.
type CloudInstance struct {
	// CreatedAt ISO 8601 timestamp
	CreatedAt Timestamp `json:"created_at"`

	// CurrentAntflyImage Currently healthy Antfly runtime image.
	CurrentAntflyImage string `json:"current_antfly_image,omitempty,omitzero"`

	// CurrentAntflyImageDigest Immutable digest for the current Antfly runtime image when known.
	CurrentAntflyImageDigest string `json:"current_antfly_image_digest,omitempty,omitzero"`

	// CurrentAntflyVersion Currently healthy Antfly runtime version.
	CurrentAntflyVersion string `json:"current_antfly_version,omitempty,omitzero"`

	// Id RFC 4122 UUID identifier
	Id UUID `json:"id"`

	// Mode Cloud deployment topology. `single` provisions one Antfly node; `replicated` provisions separate metadata and data node groups for HA.
	Mode CloudInstanceMode `json:"mode"`

	// Name Display name
	Name string `json:"name"`

	// NodeConfig Cluster node configuration. Split metadata/data node counts apply only to replicated mode; single mode is normalized to one Antfly node.
	NodeConfig NodeConfig `json:"node_config,omitempty,omitzero"`

	// OrganizationId RFC 4122 UUID identifier
	OrganizationId UUID `json:"organization_id"`

	// ProvisioningCompletedAt ISO 8601 timestamp
	ProvisioningCompletedAt Timestamp `json:"provisioning_completed_at,omitempty,omitzero"`

	// ProvisioningError Error message if provisioning failed
	ProvisioningError string `json:"provisioning_error,omitempty,omitzero"`

	// ProvisioningStartedAt ISO 8601 timestamp
	ProvisioningStartedAt Timestamp `json:"provisioning_started_at,omitempty,omitzero"`

	// Region Deployment region
	Region string `json:"region"`

	// Slug URL-safe identifier (immutable)
	Slug string `json:"slug"`

	// Status Instance lifecycle status
	Status CloudInstanceStatus `json:"status"`

	// TargetAntflyImage Target Antfly runtime image for an in-progress or manual rollout.
	TargetAntflyImage string `json:"target_antfly_image,omitempty,omitzero"`

	// TargetAntflyImageDigest Immutable digest for the target Antfly runtime image when known.
	TargetAntflyImageDigest string `json:"target_antfly_image_digest,omitempty,omitzero"`

	// TargetAntflyVersion Target Antfly runtime version for an in-progress or manual rollout.
	TargetAntflyVersion string `json:"target_antfly_version,omitempty,omitzero"`

	// Tier Customer-facing cloud package baseline used for committed-capacity billing.
	Tier CloudInstanceTier `json:"tier"`

	// UpdatedAt ISO 8601 timestamp
	UpdatedAt Timestamp `json:"updated_at"`

	// VersionPolicy Antfly runtime version policy for managed upgrades.
	VersionPolicy CloudInstanceVersionPolicy `json:"version_policy,omitempty,omitzero"`

	// VersionUpgradeCompletedAt ISO 8601 timestamp
	VersionUpgradeCompletedAt Timestamp `json:"version_upgrade_completed_at,omitempty,omitzero"`

	// VersionUpgradeError Error from the last Antfly runtime rollout.
	VersionUpgradeError string `json:"version_upgrade_error,omitempty,omitzero"`

	// VersionUpgradeStartedAt ISO 8601 timestamp
	VersionUpgradeStartedAt Timestamp `json:"version_upgrade_started_at,omitempty,omitzero"`

	// VersionUpgradeStatus Antfly runtime rollout status.
	VersionUpgradeStatus CloudInstanceVersionUpgradeStatus `json:"version_upgrade_status,omitempty,omitzero"`
}

// CloudInstanceMode Cloud deployment topology. `single` provisions one Antfly node; `replicated` provisions separate metadata and data node groups for HA.
type CloudInstanceMode string

// CloudInstanceStatus Instance lifecycle status
type CloudInstanceStatus string

// CloudInstanceTier Customer-facing cloud package baseline used for committed-capacity billing.
type CloudInstanceTier string

// CloudInstanceUsage defines model for CloudInstanceUsage.
type CloudInstanceUsage struct {
	// AcceleratorCoreHours GPU/TPU accelerator core-hours in current billing cycle
	AcceleratorCoreHours float64 `json:"accelerator_core_hours"`

	// CpuCoreHours CPU core-hours consumed in current billing cycle
	CpuCoreHours float64 `json:"cpu_core_hours"`

	// DiskGibHours Provisioned disk GiB-hours in current billing cycle
	DiskGibHours float64 `json:"disk_gib_hours"`

	// DiskUsageGibHours Disk usage GiB-hours in current billing cycle
	DiskUsageGibHours float64 `json:"disk_usage_gib_hours"`

	// InstanceId RFC 4122 UUID identifier
	InstanceId UUID `json:"instance_id"`

	// MemoryGibHours Memory GiB-hours consumed in current billing cycle
	MemoryGibHours float64 `json:"memory_gib_hours"`

	// Name Instance display name
	Name string `json:"name"`

	// ObjectstoreGibHours Cold backup/object-store GiB-hours in current billing cycle
	ObjectstoreGibHours float64 `json:"objectstore_gib_hours"`

	// Queries Query count in current billing cycle
	Queries int `json:"queries"`
}

// CloudInstanceVersionPolicy Antfly runtime version policy for managed upgrades.
type CloudInstanceVersionPolicy string

// CloudInstanceVersionUpgradeStatus Antfly runtime rollout status.
type CloudInstanceVersionUpgradeStatus string

// CloudUsageSummary defines model for CloudUsageSummary.
type CloudUsageSummary struct {
	// BillingCycleEnd End of the current billing cycle
	BillingCycleEnd time.Time `json:"billing_cycle_end"`

	// BillingCycleStart Start of the current billing cycle
	BillingCycleStart time.Time            `json:"billing_cycle_start"`
	Instances         []CloudInstanceUsage `json:"instances"`
	Totals            CloudUsageTotals     `json:"totals"`
}

// CloudUsageTotals defines model for CloudUsageTotals.
type CloudUsageTotals struct {
	// AcceleratorCoreHours Total GPU/TPU accelerator core-hours across all instances
	AcceleratorCoreHours float64 `json:"accelerator_core_hours"`

	// CpuCoreHours Total CPU core-hours across all instances
	CpuCoreHours float64 `json:"cpu_core_hours"`

	// DiskGibHours Total provisioned disk GiB-hours across all instances
	DiskGibHours float64 `json:"disk_gib_hours"`

	// DiskUsageGibHours Total disk usage GiB-hours across all instances
	DiskUsageGibHours float64 `json:"disk_usage_gib_hours"`

	// MemoryGibHours Total memory GiB-hours across all instances
	MemoryGibHours float64 `json:"memory_gib_hours"`

	// ObjectstoreGibHours Total cold backup/object-store GiB-hours across all instances
	ObjectstoreGibHours float64 `json:"objectstore_gib_hours"`

	// Queries Total queries across all instances
	Queries int `json:"queries"`
}

// ConnectionDetails defines model for ConnectionDetails.
type ConnectionDetails struct {
	// AntflyInferenceProxyUrl Colony proxy URL for accessing the attached Antfly Inference service for this instance
	AntflyInferenceProxyUrl string `json:"antfly_inference_proxy_url"`

	// DashboardUrl Colony dashboard URL for opening the hosted Antfarm UI for this instance
	DashboardUrl string `json:"dashboard_url"`

	// ProxyUrl Colony proxy URL for accessing this instance
	ProxyUrl string `json:"proxy_url"`

	// Status Instance lifecycle status
	Status CloudInstanceStatus `json:"status"`
}

// Error defines model for Error.
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail string `json:"detail,omitempty,omitzero"`

	// Errors Additional validation errors
	Errors []struct {
		// Field Field name causing the error
		Field string `json:"field"`

		// Message Error message for this field
		Message string `json:"message"`
	} `json:"errors,omitempty,omitzero"`

	// Instance URI reference identifying the specific occurrence
	Instance string `json:"instance,omitempty,omitzero"`

	// Status HTTP status code
	Status int `json:"status"`

	// Title Short, human-readable summary
	Title string `json:"title"`

	// Type URI identifying the problem type
	Type string `json:"type"`
}

// InstanceMetrics defines model for InstanceMetrics.
type InstanceMetrics struct {
	// DocumentCount Total document count across all tables
	DocumentCount int64 `json:"document_count,omitempty,omitzero"`

	// InstanceId RFC 4122 UUID identifier
	InstanceId UUID `json:"instance_id"`

	// NodeCount Number of active nodes (metadata + data)
	NodeCount int `json:"node_count,omitempty,omitzero"`

	// QueriesThisMonth Query count in current billing cycle
	QueriesThisMonth int `json:"queries_this_month,omitempty,omitzero"`

	// Status Instance lifecycle status
	Status CloudInstanceStatus `json:"status"`

	// StorageUsedBytes Total storage used in bytes
	StorageUsedBytes int64 `json:"storage_used_bytes,omitempty,omitzero"`

	// TableCount Number of tables
	TableCount int `json:"table_count"`
}

// NodeConfig Cluster node configuration. Split metadata/data node counts apply only to replicated mode; single mode is normalized to one Antfly node.
type NodeConfig struct {
	// Accelerator GPU/TPU accelerator configuration (reserved for future use)
	Accelerator struct {
		// Count Number of accelerators per node
		Count int `json:"count,omitempty,omitzero"`

		// Type Accelerator type (e.g., "nvidia-tesla-t4", "nvidia-a100")
		Type string `json:"type,omitempty,omitzero"`
	} `json:"accelerator,omitempty,omitzero"`

	// Cpu CPU request per node (e.g., "500m", "1000m")
	Cpu string `json:"cpu,omitempty,omitzero"`

	// DataNodes Number of data (storage) nodes for replicated mode; single mode is always one Antfly node.
	DataNodes int `json:"data_nodes,omitempty,omitzero"`

	// DataStorage Persistent storage per data node (e.g., "10Gi", "50Gi")
	DataStorage string `json:"data_storage,omitempty,omitzero"`

	// Memory Memory request per node (e.g., "4Gi", "8Gi")
	Memory string `json:"memory,omitempty,omitzero"`

	// MetadataNodes Number of metadata (Raft consensus) nodes for replicated mode; ignored for single mode.
	MetadataNodes int `json:"metadata_nodes,omitempty,omitzero"`

	// MetadataStorage Persistent storage per metadata node (e.g., "2Gi", "5Gi")
	MetadataStorage string `json:"metadata_storage,omitempty,omitzero"`

	// ReplicationFactor Raft replication factor
	ReplicationFactor int `json:"replication_factor,omitempty,omitzero"`

	// Storage Deprecated: use data_storage instead. Persistent storage per data node.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Storage string `json:"storage,omitempty,omitzero"`
}

// NodeConfigUpdate Node configuration changes for scaling. Split metadata/data node counts apply only to replicated mode; single mode is normalized to one Antfly node.
type NodeConfigUpdate struct {
	// Accelerator GPU/TPU accelerator configuration
	Accelerator *struct {
		// Count Number of accelerators per node
		Count *int `json:"count,omitempty"`

		// Type Accelerator type (e.g., "nvidia-tesla-t4", "nvidia-a100")
		Type *string `json:"type,omitempty"`
	} `json:"accelerator,omitempty"`

	// Cpu CPU request per node (e.g., "500m", "1000m")
	Cpu string `json:"cpu,omitempty,omitzero"`

	// DataNodes Number of data (storage) nodes for replicated mode; single mode is always one Antfly node.
	DataNodes int `json:"data_nodes,omitempty,omitzero"`

	// DataStorage Persistent storage per data node (e.g., "10Gi", "50Gi")
	DataStorage string `json:"data_storage,omitempty,omitzero"`

	// Memory Memory request per node (e.g., "4Gi", "8Gi")
	Memory string `json:"memory,omitempty,omitzero"`

	// MetadataNodes Number of metadata (Raft consensus) nodes for replicated mode; ignored for single mode.
	MetadataNodes int `json:"metadata_nodes,omitempty,omitzero"`

	// MetadataStorage Persistent storage per metadata node (e.g., "2Gi", "5Gi")
	MetadataStorage string `json:"metadata_storage,omitempty,omitzero"`

	// Storage Deprecated: use data_storage instead
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Storage string `json:"storage,omitempty,omitzero"`
}

// Organization defines model for Organization.
type Organization struct {
	// BillingEmail Email for billing notifications
	BillingEmail openapi_types.Email `json:"billing_email"`

	// CreatedAt ISO 8601 timestamp
	CreatedAt Timestamp `json:"created_at"`

	// Id RFC 4122 UUID identifier
	Id UUID `json:"id"`

	// Name Organization display name
	Name string `json:"name"`

	// OwnerId RFC 4122 UUID identifier
	OwnerId UUID `json:"owner_id"`

	// Settings Extensible organization settings
	Settings map[string]interface{} `json:"settings,omitempty,omitzero"`

	// Slug URL-safe identifier (lowercase alphanumeric with hyphens, no underscores or colons)
	Slug string `json:"slug"`

	// Status Organization status
	Status OrganizationStatus `json:"status"`

	// UpdatedAt ISO 8601 timestamp
	UpdatedAt Timestamp `json:"updated_at"`
}

// OrganizationStatus Organization status
type OrganizationStatus string

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`

	// Total Total number of items available
	Total int `json:"total"`
}

// ProvisioningEvent defines model for ProvisioningEvent.
type ProvisioningEvent struct {
	// CloudInstanceId RFC 4122 UUID identifier
	CloudInstanceId UUID `json:"cloud_instance_id"`

	// CreatedAt ISO 8601 timestamp
	CreatedAt Timestamp `json:"created_at"`

	// EventType Event type identifier
	EventType string `json:"event_type"`

	// Id RFC 4122 UUID identifier
	Id UUID `json:"id"`

	// Message Human-readable event description
	Message string `json:"message,omitempty,omitzero"`

	// Metadata Additional event context
	Metadata map[string]interface{} `json:"metadata,omitempty,omitzero"`
}

// Timestamp ISO 8601 timestamp
type Timestamp = time.Time

// UUID RFC 4122 UUID identifier
type UUID = openapi_types.UUID

// UpdateCloudInstanceRequest defines model for UpdateCloudInstanceRequest.
type UpdateCloudInstanceRequest struct {
	// ClearAntflyVersionTarget Clear a pending or failed manual Antfly runtime target without changing the live cluster image.
	ClearAntflyVersionTarget bool `json:"clear_antfly_version_target,omitempty,omitzero"`

	// Mode Cloud deployment topology. `single` provisions one Antfly node; `replicated` provisions separate metadata and data node groups for HA.
	Mode CloudInstanceMode `json:"mode,omitempty,omitzero"`

	// Name New display name
	Name string `json:"name,omitempty,omitzero"`

	// NodeConfig Node configuration changes for scaling. Split metadata/data node counts apply only to replicated mode; single mode is normalized to one Antfly node.
	NodeConfig NodeConfigUpdate `json:"node_config,omitempty,omitzero"`

	// TargetAntflyImage Explicit Antfly runtime image for a manual rollout or rollback. When set, Jobsaf patches AntflyCluster.spec.image and health-gates completion.
	TargetAntflyImage string `json:"target_antfly_image,omitempty,omitzero"`

	// TargetAntflyImageDigest Optional immutable digest for the manual target image.
	TargetAntflyImageDigest string `json:"target_antfly_image_digest,omitempty,omitzero"`

	// TargetAntflyVersion Explicit Antfly runtime version for a manual rollout or rollback. Requires target_antfly_image.
	TargetAntflyVersion string `json:"target_antfly_version,omitempty,omitzero"`

	// Tier Customer-facing cloud package baseline used for committed-capacity billing.
	Tier CloudInstanceTier `json:"tier,omitempty,omitzero"`

	// VersionPolicy Antfly runtime version policy for managed upgrades.
	VersionPolicy CloudInstanceVersionPolicy `json:"version_policy,omitempty,omitzero"`
}

// User defines model for User.
type User struct {
	// AvatarUrl Profile picture URL
	AvatarUrl *string `json:"avatar_url,omitempty"`

	// CreatedAt ISO 8601 timestamp
	CreatedAt Timestamp `json:"created_at"`

	// DisplayName User display name
	DisplayName string `json:"display_name"`

	// Email User email address
	Email openapi_types.Email `json:"email"`

	// Id RFC 4122 UUID identifier
	Id UUID `json:"id"`

	// LastLoginAt ISO 8601 timestamp
	LastLoginAt Timestamp `json:"last_login_at,omitempty,omitzero"`

	// Settings Extensible user settings
	Settings map[string]interface{} `json:"settings,omitempty,omitzero"`

	// Status User account status
	Status UserStatus `json:"status"`

	// UpdatedAt ISO 8601 timestamp
	UpdatedAt Timestamp `json:"updated_at"`
}

// UserStatus User account status
type UserStatus string

// InstanceId RFC 4122 UUID identifier
type InstanceId = UUID

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// OrgId RFC 4122 UUID identifier
type OrgId = UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// cookieAuthContextKey is the context key for CookieAuth security scheme
type cookieAuthContextKey string

// ListOrganizationsParams defines parameters for ListOrganizations.
type ListOrganizationsParams struct {
	// Offset Number of items to skip
	Offset Offset `form:"offset,omitempty" json:"offset,omitempty,omitzero"`

	// Limit Maximum number of items to return
	Limit Limit `form:"limit,omitempty" json:"limit,omitempty,omitzero"`
}

// ListCloudInstancesParams defines parameters for ListCloudInstances.
type ListCloudInstancesParams struct {
	// Offset Number of items to skip
	Offset Offset `form:"offset,omitempty" json:"offset,omitempty,omitzero"`

	// Limit Maximum number of items to return
	Limit Limit `form:"limit,omitempty" json:"limit,omitempty,omitzero"`
}

// ListCloudInstanceEventsParams defines parameters for ListCloudInstanceEvents.
type ListCloudInstanceEventsParams struct {
	// Offset Number of items to skip
	Offset Offset `form:"offset,omitempty" json:"offset,omitempty,omitzero"`

	// Limit Maximum number of items to return
	Limit Limit `form:"limit,omitempty" json:"limit,omitempty,omitzero"`
}

// UpdateCloudInstanceJSONRequestBody defines body for UpdateCloudInstance for application/json ContentType.
type UpdateCloudInstanceJSONRequestBody = UpdateCloudInstanceRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListOrganizations request
	ListOrganizations(ctx context.Context, params *ListOrganizationsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOrganization request
	GetOrganization(ctx context.Context, orgId OrgId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListCloudInstances request
	ListCloudInstances(ctx context.Context, orgId OrgId, params *ListCloudInstancesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCloudInstance request
	GetCloudInstance(ctx context.Context, orgId OrgId, instanceId InstanceId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateCloudInstanceWithBody request with any body
	UpdateCloudInstanceWithBody(ctx context.Context, orgId OrgId, instanceId InstanceId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateCloudInstance(ctx context.Context, orgId OrgId, instanceId InstanceId, body UpdateCloudInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCloudInstanceConnection request
	GetCloudInstanceConnection(ctx context.Context, orgId OrgId, instanceId InstanceId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListCloudInstanceEvents request
	ListCloudInstanceEvents(ctx context.Context, orgId OrgId, instanceId InstanceId, params *ListCloudInstanceEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCloudInstanceMetrics request
	GetCloudInstanceMetrics(ctx context.Context, orgId OrgId, instanceId InstanceId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCloudUsage request
	GetCloudUsage(ctx context.Context, orgId OrgId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCurrentUser request
	GetCurrentUser(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListOrganizations(ctx context.Context, params *ListOrganizationsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListOrganizationsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOrganization(ctx context.Context, orgId OrgId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOrganizationRequest(c.Server, orgId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListCloudInstances(ctx context.Context, orgId OrgId, params *ListCloudInstancesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCloudInstancesRequest(c.Server, orgId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCloudInstance(ctx context.Context, orgId OrgId, instanceId InstanceId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCloudInstanceRequest(c.Server, orgId, instanceId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateCloudInstanceWithBody(ctx context.Context, orgId OrgId, instanceId InstanceId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateCloudInstanceRequestWithBody(c.Server, orgId, instanceId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateCloudInstance(ctx context.Context, orgId OrgId, instanceId InstanceId, body UpdateCloudInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateCloudInstanceRequest(c.Server, orgId, instanceId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCloudInstanceConnection(ctx context.Context, orgId OrgId, instanceId InstanceId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCloudInstanceConnectionRequest(c.Server, orgId, instanceId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListCloudInstanceEvents(ctx context.Context, orgId OrgId, instanceId InstanceId, params *ListCloudInstanceEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCloudInstanceEventsRequest(c.Server, orgId, instanceId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCloudInstanceMetrics(ctx context.Context, orgId OrgId, instanceId InstanceId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCloudInstanceMetricsRequest(c.Server, orgId, instanceId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCloudUsage(ctx context.Context, orgId OrgId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCloudUsageRequest(c.Server, orgId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCurrentUser(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCurrentUserRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListOrganizationsRequest generates requests for ListOrganizations
func NewListOrganizationsRequest(server string, params *ListOrganizationsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetOrganizationRequest generates requests for GetOrganization
func NewGetOrganizationRequest(server string, orgId OrgId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "org_id", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListCloudInstancesRequest generates requests for ListCloudInstances
func NewListCloudInstancesRequest(server string, orgId OrgId, params *ListCloudInstancesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "org_id", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/cloud/instances", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCloudInstanceRequest generates requests for GetCloudInstance
func NewGetCloudInstanceRequest(server string, orgId OrgId, instanceId InstanceId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "org_id", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "instance_id", instanceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/cloud/instances/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateCloudInstanceRequest calls the generic UpdateCloudInstance builder with application/json body
func NewUpdateCloudInstanceRequest(server string, orgId OrgId, instanceId InstanceId, body UpdateCloudInstanceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateCloudInstanceRequestWithBody(server, orgId, instanceId, "application/json", bodyReader)
}

// NewUpdateCloudInstanceRequestWithBody generates requests for UpdateCloudInstance with any type of body
func NewUpdateCloudInstanceRequestWithBody(server string, orgId OrgId, instanceId InstanceId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "org_id", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "instance_id", instanceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/cloud/instances/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetCloudInstanceConnectionRequest generates requests for GetCloudInstanceConnection
func NewGetCloudInstanceConnectionRequest(server string, orgId OrgId, instanceId InstanceId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "org_id", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "instance_id", instanceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/cloud/instances/%s/connection", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListCloudInstanceEventsRequest generates requests for ListCloudInstanceEvents
func NewListCloudInstanceEventsRequest(server string, orgId OrgId, instanceId InstanceId, params *ListCloudInstanceEventsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "org_id", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "instance_id", instanceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/cloud/instances/%s/events", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCloudInstanceMetricsRequest generates requests for GetCloudInstanceMetrics
func NewGetCloudInstanceMetricsRequest(server string, orgId OrgId, instanceId InstanceId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "org_id", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "instance_id", instanceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/cloud/instances/%s/metrics", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCloudUsageRequest generates requests for GetCloudUsage
func NewGetCloudUsageRequest(server string, orgId OrgId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "org_id", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/cloud/usage", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCurrentUserRequest generates requests for GetCurrentUser
func NewGetCurrentUserRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/me")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListOrganizationsWithResponse request
	ListOrganizationsWithResponse(ctx context.Context, params *ListOrganizationsParams, reqEditors ...RequestEditorFn) (*ListOrganizationsResponse, error)

	// GetOrganizationWithResponse request
	GetOrganizationWithResponse(ctx context.Context, orgId OrgId, reqEditors ...RequestEditorFn) (*GetOrganizationResponse, error)

	// ListCloudInstancesWithResponse request
	ListCloudInstancesWithResponse(ctx context.Context, orgId OrgId, params *ListCloudInstancesParams, reqEditors ...RequestEditorFn) (*ListCloudInstancesResponse, error)

	// GetCloudInstanceWithResponse request
	GetCloudInstanceWithResponse(ctx context.Context, orgId OrgId, instanceId InstanceId, reqEditors ...RequestEditorFn) (*GetCloudInstanceResponse, error)

	// UpdateCloudInstanceWithBodyWithResponse request with any body
	UpdateCloudInstanceWithBodyWithResponse(ctx context.Context, orgId OrgId, instanceId InstanceId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateCloudInstanceResponse, error)

	UpdateCloudInstanceWithResponse(ctx context.Context, orgId OrgId, instanceId InstanceId, body UpdateCloudInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateCloudInstanceResponse, error)

	// GetCloudInstanceConnectionWithResponse request
	GetCloudInstanceConnectionWithResponse(ctx context.Context, orgId OrgId, instanceId InstanceId, reqEditors ...RequestEditorFn) (*GetCloudInstanceConnectionResponse, error)

	// ListCloudInstanceEventsWithResponse request
	ListCloudInstanceEventsWithResponse(ctx context.Context, orgId OrgId, instanceId InstanceId, params *ListCloudInstanceEventsParams, reqEditors ...RequestEditorFn) (*ListCloudInstanceEventsResponse, error)

	// GetCloudInstanceMetricsWithResponse request
	GetCloudInstanceMetricsWithResponse(ctx context.Context, orgId OrgId, instanceId InstanceId, reqEditors ...RequestEditorFn) (*GetCloudInstanceMetricsResponse, error)

	// GetCloudUsageWithResponse request
	GetCloudUsageWithResponse(ctx context.Context, orgId OrgId, reqEditors ...RequestEditorFn) (*GetCloudUsageResponse, error)

	// GetCurrentUserWithResponse request
	GetCurrentUserWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCurrentUserResponse, error)
}

type ListOrganizationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data []Organization `json:"data"`
		Meta PaginationMeta `json:"meta"`
	}
	JSON401 *Unauthorized
}

// Status returns HTTPResponse.Status
func (r ListOrganizationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListOrganizationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListOrganizationsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetOrganizationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Organization
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetOrganizationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOrganizationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetOrganizationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListCloudInstancesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data []CloudInstance `json:"data"`
		Meta PaginationMeta  `json:"meta"`
	}
	JSON401 *Unauthorized
	JSON403 *Forbidden
}

// Status returns HTTPResponse.Status
func (r ListCloudInstancesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCloudInstancesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListCloudInstancesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetCloudInstanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CloudInstance
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetCloudInstanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCloudInstanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCloudInstanceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateCloudInstanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CloudInstance
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r UpdateCloudInstanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateCloudInstanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateCloudInstanceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetCloudInstanceConnectionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConnectionDetails
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetCloudInstanceConnectionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCloudInstanceConnectionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCloudInstanceConnectionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListCloudInstanceEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data []ProvisioningEvent `json:"data"`
		Meta PaginationMeta      `json:"meta"`
	}
	JSON401 *Unauthorized
	JSON403 *Forbidden
	JSON404 *NotFound
}

// Status returns HTTPResponse.Status
func (r ListCloudInstanceEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCloudInstanceEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListCloudInstanceEventsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetCloudInstanceMetricsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *InstanceMetrics
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetCloudInstanceMetricsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCloudInstanceMetricsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCloudInstanceMetricsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetCloudUsageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CloudUsageSummary
	JSON401      *Unauthorized
	JSON403      *Forbidden
}

// Status returns HTTPResponse.Status
func (r GetCloudUsageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCloudUsageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCloudUsageResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetCurrentUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *User
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r GetCurrentUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCurrentUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCurrentUserResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListOrganizationsWithResponse request returning *ListOrganizationsResponse
func (c *ClientWithResponses) ListOrganizationsWithResponse(ctx context.Context, params *ListOrganizationsParams, reqEditors ...RequestEditorFn) (*ListOrganizationsResponse, error) {
	rsp, err := c.ListOrganizations(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListOrganizationsResponse(rsp)
}

// GetOrganizationWithResponse request returning *GetOrganizationResponse
func (c *ClientWithResponses) GetOrganizationWithResponse(ctx context.Context, orgId OrgId, reqEditors ...RequestEditorFn) (*GetOrganizationResponse, error) {
	rsp, err := c.GetOrganization(ctx, orgId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOrganizationResponse(rsp)
}

// ListCloudInstancesWithResponse request returning *ListCloudInstancesResponse
func (c *ClientWithResponses) ListCloudInstancesWithResponse(ctx context.Context, orgId OrgId, params *ListCloudInstancesParams, reqEditors ...RequestEditorFn) (*ListCloudInstancesResponse, error) {
	rsp, err := c.ListCloudInstances(ctx, orgId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCloudInstancesResponse(rsp)
}

// GetCloudInstanceWithResponse request returning *GetCloudInstanceResponse
func (c *ClientWithResponses) GetCloudInstanceWithResponse(ctx context.Context, orgId OrgId, instanceId InstanceId, reqEditors ...RequestEditorFn) (*GetCloudInstanceResponse, error) {
	rsp, err := c.GetCloudInstance(ctx, orgId, instanceId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCloudInstanceResponse(rsp)
}

// UpdateCloudInstanceWithBodyWithResponse request with arbitrary body returning *UpdateCloudInstanceResponse
func (c *ClientWithResponses) UpdateCloudInstanceWithBodyWithResponse(ctx context.Context, orgId OrgId, instanceId InstanceId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateCloudInstanceResponse, error) {
	rsp, err := c.UpdateCloudInstanceWithBody(ctx, orgId, instanceId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateCloudInstanceResponse(rsp)
}

func (c *ClientWithResponses) UpdateCloudInstanceWithResponse(ctx context.Context, orgId OrgId, instanceId InstanceId, body UpdateCloudInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateCloudInstanceResponse, error) {
	rsp, err := c.UpdateCloudInstance(ctx, orgId, instanceId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateCloudInstanceResponse(rsp)
}

// GetCloudInstanceConnectionWithResponse request returning *GetCloudInstanceConnectionResponse
func (c *ClientWithResponses) GetCloudInstanceConnectionWithResponse(ctx context.Context, orgId OrgId, instanceId InstanceId, reqEditors ...RequestEditorFn) (*GetCloudInstanceConnectionResponse, error) {
	rsp, err := c.GetCloudInstanceConnection(ctx, orgId, instanceId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCloudInstanceConnectionResponse(rsp)
}

// ListCloudInstanceEventsWithResponse request returning *ListCloudInstanceEventsResponse
func (c *ClientWithResponses) ListCloudInstanceEventsWithResponse(ctx context.Context, orgId OrgId, instanceId InstanceId, params *ListCloudInstanceEventsParams, reqEditors ...RequestEditorFn) (*ListCloudInstanceEventsResponse, error) {
	rsp, err := c.ListCloudInstanceEvents(ctx, orgId, instanceId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCloudInstanceEventsResponse(rsp)
}

// GetCloudInstanceMetricsWithResponse request returning *GetCloudInstanceMetricsResponse
func (c *ClientWithResponses) GetCloudInstanceMetricsWithResponse(ctx context.Context, orgId OrgId, instanceId InstanceId, reqEditors ...RequestEditorFn) (*GetCloudInstanceMetricsResponse, error) {
	rsp, err := c.GetCloudInstanceMetrics(ctx, orgId, instanceId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCloudInstanceMetricsResponse(rsp)
}

// GetCloudUsageWithResponse request returning *GetCloudUsageResponse
func (c *ClientWithResponses) GetCloudUsageWithResponse(ctx context.Context, orgId OrgId, reqEditors ...RequestEditorFn) (*GetCloudUsageResponse, error) {
	rsp, err := c.GetCloudUsage(ctx, orgId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCloudUsageResponse(rsp)
}

// GetCurrentUserWithResponse request returning *GetCurrentUserResponse
func (c *ClientWithResponses) GetCurrentUserWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCurrentUserResponse, error) {
	rsp, err := c.GetCurrentUser(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCurrentUserResponse(rsp)
}

// ParseListOrganizationsResponse parses an HTTP response from a ListOrganizationsWithResponse call
func ParseListOrganizationsResponse(rsp *http.Response) (*ListOrganizationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListOrganizationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data []Organization `json:"data"`
			Meta PaginationMeta `json:"meta"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseGetOrganizationResponse parses an HTTP response from a GetOrganizationWithResponse call
func ParseGetOrganizationResponse(rsp *http.Response) (*GetOrganizationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOrganizationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Organization
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseListCloudInstancesResponse parses an HTTP response from a ListCloudInstancesWithResponse call
func ParseListCloudInstancesResponse(rsp *http.Response) (*ListCloudInstancesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCloudInstancesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data []CloudInstance `json:"data"`
			Meta PaginationMeta  `json:"meta"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseGetCloudInstanceResponse parses an HTTP response from a GetCloudInstanceWithResponse call
func ParseGetCloudInstanceResponse(rsp *http.Response) (*GetCloudInstanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCloudInstanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CloudInstance
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUpdateCloudInstanceResponse parses an HTTP response from a UpdateCloudInstanceWithResponse call
func ParseUpdateCloudInstanceResponse(rsp *http.Response) (*UpdateCloudInstanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateCloudInstanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CloudInstance
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetCloudInstanceConnectionResponse parses an HTTP response from a GetCloudInstanceConnectionWithResponse call
func ParseGetCloudInstanceConnectionResponse(rsp *http.Response) (*GetCloudInstanceConnectionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCloudInstanceConnectionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConnectionDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseListCloudInstanceEventsResponse parses an HTTP response from a ListCloudInstanceEventsWithResponse call
func ParseListCloudInstanceEventsResponse(rsp *http.Response) (*ListCloudInstanceEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCloudInstanceEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data []ProvisioningEvent `json:"data"`
			Meta PaginationMeta      `json:"meta"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetCloudInstanceMetricsResponse parses an HTTP response from a GetCloudInstanceMetricsWithResponse call
func ParseGetCloudInstanceMetricsResponse(rsp *http.Response) (*GetCloudInstanceMetricsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCloudInstanceMetricsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest InstanceMetrics
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetCloudUsageResponse parses an HTTP response from a GetCloudUsageWithResponse call
func ParseGetCloudUsageResponse(rsp *http.Response) (*GetCloudUsageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCloudUsageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CloudUsageSummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseGetCurrentUserResponse parses an HTTP response from a GetCurrentUserWithResponse call
func ParseGetCurrentUserResponse(rsp *http.Response) (*GetCurrentUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCurrentUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest User
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7D1pd9s4kn8Fjzsfkh1SlB072+P9sJN73JPD69jT7206q4bIkoQ2CbAB0I7aT/99Hg7eoC5btvr4ZEsE",
	"UYW6q1CAbr2IpRmjQKXwTm69DHOcggSuP51SITGN4DRWn2IQESeZJIx6J96rhOUxInYEOn3t+R5RDzIs",
	"Z57vUZyCd+IVA0Yk9nyPwy854RB7J5Ln4HsimkGK1eR/4TDxTrz/CCt8QvNUhJeXp6+9xcL33pOUyC4q",
	"H/A3kuYponk6Bo7YBBEJqUCSIQ4y57RA7Zcc+LzCLdHT1bGIYYLzRHonh0PfS8203snBUH0i1H7yPTnP",
	"zNokTIFr1D5NJgIcuH3s4iSuSNaDETOzOFGq4zB048CnLk594lNMya9YfezlE+PTe2DRQr0vMkYFaAF6",
	"ieNz+CUHoSkTMSqB6n9xliUk0iiFPwuF5u2akN5wzrgB1VzmSxwjboEtfO8t42MSx0B3D7kCtfC9j0y+",
	"ZTmNdw/2I5NookEtfO+S4lzOGCe/wgOAbkBTj+0bakJtGArLoW0KZxlwSYxIRBywhHiE5SroFyQFIXGa",
	"qfVFOedA5QhTOUnmI5LiKTiMkhmVzNEMcCJnc/RCj0c8p5KkgPR7AyX2eZLgcQKFmFt1EpITOu0DOIrJ",
	"1MpyE+5pmuZSTYfMCDRhHMkZIDuLEw10MwOKrii7odtgdA1cEMPNDYlg31RA4RtOMwXTux4ODgfDdfAg",
	"8XrWwPdSFsOqsQ1x+aBeWBRGqb2w10RkCZ4j/bSO+4c5OuMsziNt4l6/9BxYUxbDKGJ0QqarUPrIYnhl",
	"Ri58ZRlL8zlaf+0ZZ9dEkZnQ6UiNS2ALsW/MAlodO2TRWopSEEIJFZmg+ktogkkC8Tp8bcASEvMt8OUw",
	"dcrka8gSNk+VKtghdf7lIgAs5LGLbyLJp935Ls/fBwJPAJEYqCQTAhw9IYUWPm3Mns6DrJSOIB47oUgs",
	"c7GRrH42ryx8T2I+hVWm6UIPchsCZS0wRYQqRKcchECKo5jmOEGcJQnL5VomwoHJ5jZLLsF0Q5PVxKfX",
	"YrlpY4evTZ2WLTtYC0ECfCOuX6gXFr6XZ/E2bsyuaZSxhETzjSD/y7x6Zt6szZVnU461cdvSyLQnWmpn",
	"JpylWkwSLDos20RW21C3tDiOaTbVZEvZSzNDodeLeiz8xdPBcdsXWE9lrZQVJ+v3SqNSWkW/Hvw0ROhr",
	"SR82/hkiHcB2HWNPDhZXtlWyjCVsOh+gnwSh0wR+qpyBQIxCwTDlDf8b/cTBhIYQNwYKUHmgBJSCxDGW",
	"GGEaI/2PehFNOcszoRXzHy+06lGVlXzxDFC94mLi2toq3rsMaddAFbllQiYQzaMEUEnRAmAGNFZzNr2X",
	"RgDH84LI5qsYNH8V10Qu1Jv6/xhar8agtcjzPes7V67gwlqRdhwmJEuBBxMcKU8caW5lOLpSlnSMBSSE",
	"AsoFxJqUEUtTIiXEQYQzHBE5R2OSJIROGyTWasKNeNEY89gsfjWWl8I6pmZAjqMIEuBYMj6KGIfRjOXc",
	"wY53Z5fhxdklqo1HanygxyNCy2DXYo00zxQZGU+VVnsxy8f6G4uoSdh1bJvlS4G/OrusA4sYFXkK8R2h",
	"xkRcjaZk3Af1rBAMiJEai96Rl/eyXA04V/xYBv61AqlH3Rvgejlm3SAeUsbny/D8oEfUcLwn9rizgNIs",
	"xM10oCP8xpQKqcRqCfavWBKjMY6u8iw0rwT6nXuj+S85cKtrTcj/mwOfo4jlVC4D4aj0NBxTo8JmiVHA",
	"7GiWg58dPeiRzz6K+n0mZKVXa4Y0Hfr0xIMmdtImM8UUTyFG1vmLuqHMCKXaimdYRrMRziXzdAmN8fID",
	"/pnxkYkkV9tPZ5iwCmkbEVnPVcePxJq7lQdTQ81/Zc42Tlh0tcwDaZv+OU9TzOdd024laaQlaQTUURx8",
	"Q2PEJo1aRb+IYwmBWpVL25qwtJfqQvusvr4feIXY64Xq2upGMZ9xhotyYsw51lG1ZBIn682l57gw49ta",
	"6SKH72BIfSEl8F7FqUPc2pHr99EKd44jzoRAOElQHcF7cOUGfMuhbw9ulQ834LJ+T35H0Cu9uEEgdvny",
	"7UGvdsoGbNp2zduDXNOdGrjRaqe6PSa9DtXAto/7AKxwp/vrORmloGtYr0Fi4rQAtu5DJ8BBhQQZZ9/m",
	"o5wnzrCH0TnSI9Dl+XtTZokiECqJ0wYaS4mjGcRF0nhazIsE8GsSgS0ZEVESuFGGmUmZiZMwzBIsFVsH",
	"Br8BYaHOhcLrgxCPo4PDZ0EMk6Pj5yEm4fVBXQhyTlzGP8ZiNmaYx0vXVo4q18cyoMXqZkxIuzbMU3R5",
	"etfVlELWXNQay7kLm+6N+GvgeYcqaUvLqhW3mekvk+ISBZeCvCnKVk2liLW2dCn7jzzFNOCAY10EhW9Z",
	"gqnZJBUZRGRCIiSZoTCLTLDSovGbFJME4TjWRUkiULlEB/F0Vc0VMMYxUf/iBF3jhMQGBTvar0Kb5qom",
	"BBJHOPdWfa0zIhThvNRkU9FzIGV3DVZtKpSaYcB2JmpxtxhVzO7iVjvuIrUdw3at/xRxKEyPLfjPi6WV",
	"vOrh0RI9wJkyN2EugIvw+HgI3x0NhwEc/m0cHB3ERwH+r4PnwdHR8+fHx0dHw+FwuJGKtKTt4uLMJgEo",
	"MuXBEsejoWM/3/ckkYmDHJ9njEsfzZriK2wOUF/6vypxetMnAOYLF8nbhM44GyeQIv3GmhQ2UhxWch0U",
	"kricji15siANQZbagLJeCpKTyKE3MYvyFKgc6bS7N1qzo2xyXosk9I5JI04hVD4/8lwM3KLYYncpnahV",
	"rSQ4kuQadC1WoCdlkfavukT71ImLDWtGSotHKaNydm/1iDvunqmgSIVLuYB4NJ7L/sDOjjQVU0KRGbwW",
	"KzTbVhO25O5GNZeyKl2H4pLO2sayo5afCwncFNjNPnXOtc4M0OcsIbIsxodVIV6DEghnWTJHjCZz0/NU",
	"1N5Rqsv8piqvPygnRRW5EvIrxGp0a1NgYKrJ7rRy3aJwDXn0hIOKFm2Ne5LLnGsOPu0AWkPsSyACZZZW",
	"3vLWrD4L96KGsBqBnsBgOvDRjx69JjHBgQSR4EAe/ejVvsQHw+GP3lOnwepwO8pydyHbdimVS6hgHw+H",
	"qQF4MNT/Nney1WN3OCzxSFuDRsfYgd9LSi1CT6xCPbWWRDFolfDg5AbPhUtqlnNBo2jhOQrtwAURUlmb",
	"QskVcSpBLyl0MHxHDIWO9X9NAqmn7jBHZW69let+hhwV0L7rAjvqg2XU1MGQYT9DSiP+5BxPpK6gAxW5",
	"WMobMqWMW82q8anBDWdoUeK4KUdKNJtkOiyZ0iXToZtMxWIIo6MJjkrrYkn1rE0qTZbaS8i+tErwGivM",
	"OJhNSbsp3WlSsc9PlIVCdQrpJAtwPECrZHWwhkQuljqHS70x7LCEHdeAohmmUyseIsJ6s/C37C524BSG",
	"vb0IhZT43rdgygL1bSCuSBawzCRkQcbUGO6dTHAiYGfOZHmvxNrodaRqg4Xdl7Na6Zv+AP5ol+5nLXfz",
	"x3Axjtz7Xk39ema73l3fvwMHqbMGZQpIirZFkkWZJBPr4kTDk9gRf8dRCoOIpfXEx0zv6hnertt6g4TV",
	"uUffOHIQ97XtvohSQK8Yz/RW7Lf3QKcqLS2OW5SfXXv7NxT4Bnm1ACkJnRoPVRbczmq8cknJm28SqCDj",
	"BFC98wuVs/Wa7ko+NuhfTdgN8AgLQDjJZpjmKXASoRsiZ2g2z2ZAhY8oQzmNgYuIcdCdkBFLGBXNoEsJ",
	"SRB1SHvcoWyGpQSuUPr/Lzj4dRj87etfn/zPSVB+ePqff9m+FFyXgyrj36p30tWO12y+K2XCb6ldLUPf",
	"pAHPgfxyQe90p5k6jVJUzn4FWustc23on+EpMQXoDyBx15Ykxemn5Z6NlSeRlhtovdfcV2ppH6XC15gY",
	"OV95CqnOpfI8U3HUygB1Ufus1oT35toeXWnFggnL49EWVbUtrSAoNEbukE+jaIK9SoUbKhiZgs7IAvfu",
	"dpKir07f3sXQaNWHrNGJW3jczYxjbd/CQNVHjr7J1UbRpcpd3jbo3+ChS3wqxnUbxj5/Qt89Hx4gWY5p",
	"5KfDw+PgYBgMDy8Ojk+eDU+Gw/9buwtF86cD8fztK3R0cHiI1OM++dh4wyEnTiEy2WKjuFo7c9fWIMC8",
	"1Y4/Mk36rookYI4wsh1KytWYxqSi977V6mTPDSh3xXJpUtNi8yAh14CsRlSHsOxaxowlgOkOTgx9hJt2",
	"+LFhoLHVsSGbwK97NOTNNxV0k2WHQ1rHHRQv1L9jHF0N0A8z0DGJj75nY4EnSHe8gbDz2cryQGQQDcyc",
	"mMb2cFgwxRIEsmcHOqfCchFEQCXHyUEQs+gK+CC7mg5iuA7NmgI9YYC5JBMcSREqK4AJBS7siJPyNMad",
	"jqt8sqkrIn3nViyJrBiWQlYtRszw4fHzE7Pr7W1/XKWPX40DK0s5dm7Mn0AOCvQcZbm/oyv3dwbFlQ9d",
	"CnBswuNrLDF3tziccTYhCaCMRHpz4PL8vXN/0X6jcp/QzDf4OZt29xLvqZqyddhgDc7IbZIUffpTou/Z",
	"jKLXbAtD1ZNhanBQ71No6Tfwv9cI60oqa4gcHh/fKYxJsJCjhE0J3ZSod07g1Eo3S9zWynAUfXeQ2RS0",
	"b8jSlnlMDUW3eODI7Pn25y/N8zJ9KYxmU5RzIuef1TLtHQCAOfAXudlxHutPbwsZ+/6HC6/NtO9/uECS",
	"XQE1Z80+qVfRJGE3yoa+ODtFVzAvrkjQ4YOesjKRyl6Yhjl2RaAA3GqiAKFNdaTHKLlAca5WgbR0Fnck",
	"mMfVLQmm8WqksasA4oz8E+bmnDyhE1acv8eRFgP7rnUW5szW5zzLmG4J1iZxSQ+F1zl8f5aPExLZ3nfd",
	"pfDi7NSU7xow6iUL4RcVJh/hXM5URGqKTH7RCFe2r/n2/fOXL175tolT+Cg1LRW+Dh50h+NAJ3YRUAG1",
	"dSqd5AQk5vNaF0tz+Wd2mQpzr/RI3ol3MBgOhjqLzYDijHgn3rPBcPDMtPHPtECFhxMcGrSCqCh66j1m",
	"LryTLw73Ys/+dqitKFHvB8rlLLw+8BZfF76BEhNhbMSuAAiQeba76a+Bk8l81/MHhhk7B7NDYulPgkwp",
	"y+XWEHpbzCwQbdRDs2W3m2VYCCoJ4eluQBB6TaSxKeGtNoSLnRHMAStUJjiTDwqSg7BnZ3YC0nicnTAr",
	"hV3Nq78IUpAzFu/IADP98VYf3YiBL8IIm/zpgcAlhD4YqN2JQAdWTne4sHrIoUA4C0vviZDN6ATdzIDb",
	"GJ0IlTyDPuyh4wDTGXAa2zc/NWD4jSvLvriD7mpIaO/pWvgrR5rLxhZfW1daHQ6HG92v1Go/tWXWtQ6s",
	"NbYWHS3Tqd0mWDZHa1OhnWxofOxM3dyhe/FTg/goIeauraPhQR8eJe3C7p1RNlfQbKtnCV++Kqrfu61V",
	"aYw9KOkQQd2+qfLLL81Fel8X/m7sfgN8GM0gugqK3cIHAHhrrnxb9KrpO2iSCMX23FFbK99BQyk310l9",
	"b92dNW19VVou1+U6t5Ns9dKz1S81Lo07Gh6tfqO8We6xlactGI+tOoUkhziPiQwSNhUPrEOhTa7DiING",
	"AeKpKYM+BhK6VhPoLVfxuDhwiBiPHw8JafsoHxK4OV2HMxJcwVw8LvTw9grmhZHfAzRCzh6PJeZ+nbS4",
	"6vbhEQAhSfpoyzeXNj0m7PBW/308eeygEZo8Q+wZOuGtyoQej06NuzX6UzicJPZSq/KF4rK+VnjQzeIa",
	"24pi25DR/13le82bc/cj4Wte8/1wMfE+5Ict2a6FuZXgPnSI275q4LbWMrU8lWuupkhyEKFRkuv+Hns6",
	"GdMYReVdE0hvaDkyvqaw7kx/a1fQ7zRBbOneKkX4M0dcI0dsSlyv+uhuJcfWtN7VrijeOVZKcQq+PvWk",
	"D5M2JdTRFfeAQqrb716yeH5v8rmky2/RtPGS57DYI02x3QlGhIerRbj2mwF/KpdbuaxqrKlfe+OeHjkp",
	"XoXVIyfLa6P3qEl0H5a2H0MZiThP9hI5sZdIhbfmn5Gple2f/PXjGcbshiYMx/uFcBW8Lo+Hqxj38vy9",
	"DnvVNNygKuyVzGYMnZqroKBubZeHxNV1bb+D4Lhz9ZzL7Vf0/DM4XiM47pJr/x24PpEjlqpV48dHlFJV",
	"t7ebt217fCd4WVEjemNAP4gu/b7KSt2TdftRWqrjZWXjT4uxrB6VOQhW2QytLcW9Z/tlNqYcP9qmy3Kc",
	"wlv9d/+irrS6wK7X1Nr7Cnx94+3cNGbrSxPM0a6iY3s9g9uOXwpJ+s0HL+0FOSxR+ZMCBdX/NEP9gQtp",
	"E+s3YYIssmGGKSQ7MUV+Z4+MRThBr+EaEpalSo7rs52EYaIGzJiQJ98Nvzu8x0WaXxX9fa6xdIL7Za85",
	"6Mu99xIpsZ9Yhbf2v/3zvvYe0EfBSUQkfdRmjby4aaK/dOK6Gdb+uoEONhyNAYSu7AsoQhDz2xx72EXa",
	"/ckV12/jajIUPvMPsl9ebffllnl7FBOYC77LnpoQS8nJOJcPr+GP1G5UthWZfx7D3jpQCOv3zjwkLiIf",
	"1wA8HuwwY9zewfSQKEiOqZgAD/SFWWJGsofGoPQwDw40nBEVcsx3BjzDQtwwHu/0mGcJZML4lMkdA+Fg",
	"7xPbIYydQTBnNwN9gtg6/d0AEmRKd3U62TiwtD8oOweZcyrqR/shNsfpMnO7ijPYMmGcvrFlh1GTnt8Z",
	"KNXQ+02eIqvHwrmhYhH2qMXtMN4pJKJ+XnlnNs0evy9vmLlnAV/shEuWEUsvPKmu0Kiu+DCM871vgb17",
	"5WP9+24FpHFyzDVh+7xqe+Lm8y6AF3lMJErY1P7sUzWzfuKY0XyvZioH1m/8cL7RGNBF4nMtbHGusj7A",
	"tcrm8y6AlzaV1Ed2dCVb4SMTc8FJDJH5aeoKoH3BAap40gViUjPJcXRV7E7+kjOJRZ39Jn3pst/8XuTt",
	"8ma3arPTRaR6v3sbwGmtxbojAubSm/qVL7o7odOfbOFopF6cnf4T5i5Qjceumt6URNj+1A3iMCVC8vka",
	"EC+KX09xArRPu/Da1XfD/WJ7qw6g2pNwQigr/F3p0q0remJbc9qMli9tA1EP4OLxSvGwP5yu8LB7Yk04",
	"5y9fvOoDop/1Qej/7XDTz62PJXZW1atCjccOmzdWBhuPSaIA1beZlpOx8V4f2OagLnB9Z3YZOerlmSui",
	"ipubLMT39mMbiPneZRyAF9JurLmWQ311WiN8rGyeCfkcxs486MK4uGGB+d2K1i1MSN9toyG6YV3csLfF",
	"D160wVXPuhDPCjrV5P2JSRt8pCN73/6IhK9weFpBLN50ACwf9XDHzqgv7aomfGPvNGvPZr7vYYiNDzVl",
	"FMlQceWIX7tvyga4HTSL2PKreibx9J2tqn5xX8qlAX5oXKvViej8jj8vvHDLh36t+986lMLTNWdv+89K",
	"N43n6Z2uOU3dw7S8QNNEt+xpy8rVjVHDFtTRsD9NadCwU7XQcSi0YyFae5svFspbqlhd/muSWchUweqv",
	"i6+LfwcAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
